name: Main
on:
    push:
    pull_request:
        branches:
            - 'main'

jobs:
    server:
        name: Build server
        runs-on: ubuntu-22.04
        steps:
            - uses: actions/checkout@v3
              with:
                  submodules: 'recursive'
                  fetch-depth: 0

            - uses: actions/setup-dotnet@v3
              with:
                dotnet-version: '7.0.x'

            - run: dotnet build ./server/server.sln
